### PR TITLE
Add support for any props of <error> tag

### PR DESCRIPTION
**Pull request by gucong3000**

### CODE REVIEW

**Comment by jimf** [comment]
Thanks! I'll publish to npm later today or tonight.

**Comment by jimf** [comment]
Actually, before publishing, I need to step back a second. This has the potential to be a breaking change, since this change may result in the library adding potentially invalid attributes to the xml. I can't find a hard spec for what the resulting xml must conform to, but I was able to track down the [official Java writer code](https://github.com/checkstyle/checkstyle/blob/f78225900c05a26640c5d4e13b697f3009b4a04d/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L200-L219), which seems to indicate that only `line`, `column`, `severity`, `message` and `source` are valid. Furthermore, it looks like `column` is omitted if it's 0, which I'm not currently adhering to. I also don't know whether the checkstyle version (which is currently hardcoded to 4.3) is influential in which keys are expected/supported.

**Comment by jimf** [comment]
Okay, I've pushed an update that treats `line`, `column`, `severity`, and `message` as required, `source` as optional, and ignores anything else. I'm cool with publishing at this point. Did you have any other updates you were hoping to get in?

**Comment by gucong3000** [comment]
> Did you have any other updates you were hoping to get in?

No.

**Comment by jimf** [comment]
1.1.0 published. Thanks again!

**Pull request merged**
